export const UPDATEPAGELOADING = "UPDATEPAGELOADING";
export const GETJOBLIST = "GETJOBLIST";
export const GETJOBDETAIL = "GETJOBDETAIL";
export const ERROR = "ERROR";
export const GETCATEGORYLIST = "GETCATEGORYLIST";
export const GETCITYLIST = "GETCITYLIST";
